"""
src/core/types.py
"""

from dataclasses import dataclass
from enum import Enum
from datetime import datetime
from typing import Optional


class Direction(str, Enum):
    """Trade direction enumeration."""
    LONG = "LONG"
    SHORT = "SHORT"
    NEUTRAL = "NEUTRAL"


class OrderType(str, Enum):
    """Order type enumeration."""
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"


class TradeStatus(str, Enum):
    """Trade status enumeration."""
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


@dataclass
class MarketState:
    """Current market snapshot for a single bar/candle."""
    symbol: str
    interval: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: Optional[float] = None
    bid: Optional[float] = None
    ask: Optional[float] = None

    def __post_init__(self):
        """Validate market state."""
        if self.high < self.low:
            raise ValueError("High must be >= Low")
        if self.close < 0 or self.open < 0:
            raise ValueError("Prices must be non-negative")


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    signal_id: str
    strategy_id: str
    symbol: str
    timestamp: datetime

    direction: Direction
    entry_price: float # Intended entry price.
    notes: Optional[str] = None


@dataclass
class Trade:
    """A completed or open trade."""
    # Identifiers
    trade_id: str
    symbol: str

    # Order details
    direction: Direction
    entry_price: float # Filled entry price (slippage included).
    entry_time: datetime
    volume: float
    status: Optional[TradeStatus] = None

    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    signal_id: Optional[str] = None
    strategy_id: Optional[str] = None
    exit_price: Optional[float] = None
    exit_time: Optional[datetime] = None

    # Performance metrics (calculated on close)
    gross_pnl: Optional[float] = None
    net_pnl: Optional[float] = None
    commissions: Optional[float] = None
    slippage: Optional[float] = None

    def __post_init__(self):
        """Validate trade."""
        if self.volume <= 0:
            raise ValueError("Size must be positive")
        if self.status == TradeStatus.CLOSED:
            if self.exit_price is None or self.exit_time is None:
                raise ValueError("Closed trades must have exit_price and exit_time")


@dataclass
class Prediction:
    """ML/filter prediction on a signal."""
    prediction_id: str
    signal_id: str
    strategy_id: str
    symbol: str

    probability: float  # 0.00 to 1.00 (likelihood signal is good)
    decision: bool 
    model_name: str
    notes: Optional[str] = None

    def __post_init__(self):
        """Validate prediction."""
        if not 0.00 <= self.probability <= 1.00:
            raise ValueError("Probability must be between 0.00 and 1.00")
